import type { InteractiveStoryPrototype } from "@/lib/interactive/types";

export const interactiveStoryMock: InteractiveStoryPrototype = {
  title: "雾城回声",
  premise:
    "失忆修书师林岚在雾城旧书店收到一封来自未来的信，每一次章末选择都会改变她与同伴的信任、城市真相的揭露顺序，以及最终进入的故事路线。",
  selectedOptionId: "B",
  currentChapter: {
    id: "chapter-03-clocktower",
    volumeTitle: "第一卷 雾灯未熄",
    chapterNumber: 3,
    title: "钟楼背面的名字",
    subtitle: "林岚第一次发现，雾城会主动抹去被记住的人。",
    readTimeMinutes: 7,
    body: [
      "雨停在午夜前一刻。旧书店的铜铃没有风也响了三声，像有人从门外伸进一只看不见的手，把整条街的时间拨慢。",
      "林岚把那封未来来信压在《雾城街志》下，纸页却自己翻到钟楼一章。插图里原本空白的背墙上，慢慢浮出一个名字：沈砚。",
      "她记得沈砚。至少她以为自己记得。那个总在傍晚送来残破手稿的青年，袖口沾着银灰色粉尘，说话时习惯先看窗外，仿佛雾里站着另一个审稿人。",
      "可当林岚冲上阁楼，翻出两人共同修补过的书脊，所有批注都只剩下她自己的笔迹。更糟的是，街对面的灯牌开始倒着发亮，一笔一画拼出警告：不要在钟声后呼唤他的名字。",
      "楼下传来钥匙入锁的轻响。顾栖推门而入，披肩湿透，手里握着一枚从钟楼墙缝中取出的铜片。铜片边缘刻着细小的路线标记，正好能嵌进未来来信的火漆印。",
    ],
    endingBeat:
      "第三声钟响即将落下。林岚必须决定，是立刻去钟楼背面追索沈砚，还是先相信顾栖带回的铜片。",
  },
  chapterDecision: {
    id: "decision-chapter-03",
    question: "第三声钟响之前，林岚要如何处理沈砚被抹去的线索？",
    options: [
      {
        id: "A",
        label: "独自前往钟楼背墙",
        description: "不惊动任何人，趁雾还没有合拢，直接确认墙上残留的名字。",
        routeHint: "偏向真相线，但会提高失踪风险。",
        effects: [
          { kind: "route", target: "真相线", delta: 18, note: "更早接触雾城抹除机制。" },
          { kind: "meter", target: "雾蚀风险", delta: 14, note: "林岚单独暴露在钟声范围内。" },
          { kind: "relationship", target: "顾栖", delta: -6, note: "顾栖会认为自己没有被信任。" },
        ],
      },
      {
        id: "B",
        label: "与顾栖交换全部线索",
        description: "展示未来来信，把铜片和火漆印拼合，再共同决定下一步。",
        routeHint: "偏向同盟线，关系稳定但真相推进稍慢。",
        effects: [
          { kind: "relationship", target: "顾栖", delta: 15, note: "双方第一次共享核心秘密。" },
          { kind: "clue", target: "铜片火漆印", note: "解锁钟楼路线图的第一段。" },
          { kind: "route", target: "同盟线", delta: 20, note: "后续章节可触发顾栖主动救援。" },
        ],
      },
      {
        id: "C",
        label: "烧掉未来来信",
        description: "阻断未来对现在的干预，观察雾城是否因此停止抹除沈砚。",
        routeHint: "偏向逆命线，短期安全，长期代价未知。",
        effects: [
          { kind: "flag", target: "拒绝未来", note: "后续选择将更难获得预警。" },
          { kind: "meter", target: "未来干预", delta: -22, note: "来信暂时失去指引能力。" },
          { kind: "route", target: "逆命线", delta: 16, note: "林岚开始主动切断预言。" },
        ],
      },
    ],
  },
  relationships: [
    {
      character: "顾栖",
      role: "雾城档案员",
      affinity: 68,
      trust: 74,
      status: "愿意共享禁书库钥匙",
      recentChange: "因选择共同拼合铜片，信任上升。",
    },
    {
      character: "沈砚",
      role: "被抹去的修稿人",
      affinity: 57,
      trust: 41,
      status: "存在痕迹不稳定",
      recentChange: "名字出现在钟楼背墙，真实关系仍待确认。",
    },
    {
      character: "钟楼守夜人",
      role: "路线看守者",
      affinity: 22,
      trust: 18,
      status: "敌意观察",
      recentChange: "林岚持有铜片后进入对方视野。",
    },
  ],
  meters: [
    {
      label: "雾蚀风险",
      value: 46,
      description: "越高越容易触发记忆缺页、场景改写和角色消失。",
    },
    {
      label: "未来干预",
      value: 63,
      description: "决定未来来信能提供多少预警，也会吸引钟楼注意。",
    },
    {
      label: "同盟稳定度",
      value: 71,
      description: "影响同伴是否会在关键分支主动介入。",
    },
  ],
  routeTendencies: [
    {
      id: "truth",
      label: "真相线",
      score: 62,
      trend: 8,
      accent: "teal",
      description: "追查雾城抹除机制，优先揭露沈砚消失的原因。",
    },
    {
      id: "alliance",
      label: "同盟线",
      score: 78,
      trend: 20,
      accent: "amber",
      description: "通过信任和协作打开禁书库、钟楼暗道等路线。",
    },
    {
      id: "defiance",
      label: "逆命线",
      score: 36,
      trend: -4,
      accent: "rose",
      description: "反抗未来来信的安排，换取更高自由度和不确定结局。",
    },
    {
      id: "echo",
      label: "回声线",
      score: 44,
      trend: 5,
      accent: "violet",
      description: "保留被抹去角色的记忆碎片，可能进入隐藏终局。",
    },
  ],
  routeTimeline: [
    {
      id: "route-01",
      chapterLabel: "第 1 章",
      title: "没有署名的未来来信",
      summary: "林岚选择保存来信，并记录第一条未来警告。",
      status: "past",
      route: "真相线",
      choice: "保存证据",
      consequences: ["未来干预 +12", "解锁旧书店暗格"],
    },
    {
      id: "route-02",
      chapterLabel: "第 2 章",
      title: "顾栖的禁书库钥匙",
      summary: "林岚没有隐瞒街志异动，顾栖首次提供内部档案。",
      status: "past",
      route: "同盟线",
      choice: "共享街志异常",
      consequences: ["顾栖信任 +11", "获得禁书库临时权限"],
    },
    {
      id: "route-03",
      chapterLabel: "第 3 章",
      title: "钟楼背面的名字",
      summary: "当前章末选择将决定先进入钟楼暗道还是禁书库回溯室。",
      status: "current",
      route: "同盟线",
      choice: "待确认",
      consequences: ["路线分歧即将记录", "沈砚存在痕迹不稳定"],
    },
    {
      id: "route-04a",
      chapterLabel: "第 4 章 A",
      title: "钟声后的空白街区",
      summary: "若单独追索钟楼，林岚将提前看见被删除的街区。",
      status: "possible",
      route: "真相线",
      consequences: ["雾蚀风险上升", "提前遭遇守夜人"],
    },
    {
      id: "route-04b",
      chapterLabel: "第 4 章 B",
      title: "禁书库回溯室",
      summary: "若选择同盟路线，顾栖会带林岚读取沈砚最后一次登记。",
      status: "possible",
      route: "同盟线",
      consequences: ["顾栖支援可用", "铜片火漆印继续解锁"],
    },
    {
      id: "route-hidden",
      chapterLabel: "隐藏",
      title: "回声终局入口",
      summary: "需要保留三段被抹去者的名字，并维持未来干预低于 40。",
      status: "locked",
      route: "回声线",
      consequences: ["条件未满足", "至少还需要 2 个记忆碎片"],
    },
  ],
  flags: ["已保存未来来信", "禁书库临时权限", "钟楼铜片已取得"],
  clues: ["火漆印缺口", "沈砚的银灰粉尘", "倒亮灯牌警告"],
};
